In [19]:
import pandas as pd
import numpy as np
from sagemaker import get_execution_role
import seaborn as sns
import matplotlib as plt

In [2]:
role = get_execution_role()
bucket='floodrisksummary'
sub_folder = 'Dataset'

In [3]:
# State
file_name = 'fsf_flood_state_summary.csv'
data_location = 's3://{}/{}/{}'.format(bucket, sub_folder,file_name)
print(data_location)
df_state = pd.read_csv(data_location)
df_state.head()

s3://floodrisksummary/Dataset/fsf_flood_state_summary.csv

,fips,name,count_property,count_fema_sfha,pct_fema_sfha,count_fs_risk_005_year00,pct_fs_risk_005_year00,count_fs_risk_005_year30,pct_fs_risk_005_year30,count_fs_risk_100_year00,...,count_floodfactor1,count_floodfactor2,count_floodfactor3,count_floodfactor4,count_floodfactor5,count_floodfactor6,count_floodfactor7,count_floodfactor8,count_floodfactor9,count_floodfactor10
0,1,Alabama,3013186,181955,6.0,129602,4.3,142493,4.7,398781,...,2507950,16182,36155,24932,40495,65119,63520,92919,119966,45948
1,2,Alaska,372298,1911,0.5,16022,4.3,17673,4.7,51308,...,301351,2991,5432,5893,6643,12716,9280,9993,11729,6270
2,5,Arkansas,1915572,149192,7.8,84484,4.4,86192,4.5,204727,...,1649346,7834,24096,16753,23506,38319,31823,44285,57412,22198
3,4,Arizona,3224944,128330,4.0,30654,1.0,33312,1.0,235211,...,2751027,72990,106751,55725,62302,63973,39564,35430,28492,8690
4,6,California,11336595,446239,3.9,140493,1.2,166242,1.5,1395118,...,8658154,210676,406648,320198,420758,593867,259966,209269,166898,90161

In [4]:
# County
file_name = 'fsf_flood_county_summary.csv'
data_location = 's3://{}/{}/{}'.format(bucket, sub_folder,file_name)
print(data_location)
df_county = pd.read_csv(data_location)
df_county.head()

s3://floodrisksummary/Dataset/fsf_flood_county_summary.csv

,fips,name,count_property,count_fema_sfha,pct_fema_sfha,count_fs_risk_005_year00,pct_fs_risk_005_year00,count_fs_risk_005_year30,pct_fs_risk_005_year30,count_fs_risk_100_year00,...,count_floodfactor1,count_floodfactor2,count_floodfactor3,count_floodfactor4,count_floodfactor5,count_floodfactor6,count_floodfactor7,count_floodfactor8,count_floodfactor9,count_floodfactor10
0,1001,"Autauga County, AL",30104,1651,5.5,1083,3.6,1160,3.9,3421,...,25656,140,348,249,398,631,579,774,1015,314
1,1003,"Baldwin County, AL",141260,19289,13.7,6965,4.9,9145,6.5,25220,...,108464,1368,2410,1633,2357,4399,3934,5248,8152,3295
2,1005,"Barbour County, AL",23235,924,4.0,1015,4.4,1081,4.7,2039,...,20731,120,163,80,141,221,243,457,814,265
3,1007,"Bibb County, AL",14959,911,6.1,1013,6.8,1063,7.1,1725,...,12968,38,94,64,127,171,195,395,660,247
4,1009,"Blount County, AL",43089,930,2.2,2730,6.3,2943,6.8,5189,...,36925,94,319,273,371,548,643,1182,1829,905

In [5]:
# Zip - code
file_name = 'fsf_flood_zcta_summary.csv'
data_location = 's3://{}/{}/{}'.format(bucket, sub_folder,file_name)
print(data_location)
df_county = pd.read_csv(data_location)
df_county.head()

s3://floodrisksummary/Dataset/fsf_flood_zcta_summary.csv

,fips,count_property,count_fema_sfha,pct_fema_sfha,count_fs_risk_005_year00,pct_fs_risk_005_year00,count_fs_risk_005_year30,pct_fs_risk_005_year30,count_fs_risk_100_year00,pct_fs_risk_100_year00,...,count_floodfactor1,count_floodfactor2,count_floodfactor3,count_floodfactor4,count_floodfactor5,count_floodfactor6,count_floodfactor7,count_floodfactor8,count_floodfactor9,count_floodfactor10
0,30165,156,20,12.8,30,19.2,31,19.9,44,28.2,...,109,2,0,1,3,3,4,5,20,9
1,31905,4,1,25.0,1,25.0,1,25.0,2,50.0,...,2,0,0,0,0,0,1,0,0,1
2,35004,5297,147,2.8,44,0.8,60,1.1,584,11.0,...,4430,39,98,54,121,157,115,158,110,15
3,35005,4716,15,0.3,71,1.5,82,1.7,407,8.6,...,4237,3,19,14,28,52,63,96,141,63
4,35006,2779,60,2.2,449,16.2,466,16.8,612,22.0,...,2134,7,6,14,13,25,32,59,129,360

In [6]:
# Congressional District
file_name = 'fsf_flood_cd_summary.csv'
data_location = 's3://{}/{}/{}'.format(bucket, sub_folder,file_name)
print(data_location)
df_county = pd.read_csv(data_location)
df_county.head()

s3://floodrisksummary/Dataset/fsf_flood_cd_summary.csv

,fips,name,count_property,count_fema_sfha,pct_fema_sfha,count_fs_risk_005_year00,pct_fs_risk_005_year00,count_fs_risk_005_year30,pct_fs_risk_005_year30,count_fs_risk_100_year00,...,count_floodfactor1,count_floodfactor2,count_floodfactor3,count_floodfactor4,count_floodfactor5,count_floodfactor6,count_floodfactor7,count_floodfactor8,count_floodfactor9,count_floodfactor10
0,101,Alabama Congressional District 1,431390,45932,10.6,19130,4.4,23239,5.4,75897,...,334485,3685,6705,4417,6455,12765,12588,17904,23260,9126
1,102,Alabama Congressional District 2,442124,20925,4.7,16342,3.7,17357,3.9,42751,...,387679,1918,4195,2577,4577,7148,6322,10013,13408,4287
2,103,Alabama Congressional District 3,470471,27180,5.8,23053,4.9,25181,5.4,59950,...,396607,2366,4939,3075,5661,8619,9370,14788,18789,6257
3,104,Alabama Congressional District 4,503319,19266,3.8,25155,5.0,26676,5.3,59700,...,429591,1947,4822,3488,5306,8335,7937,12389,19253,10251
4,105,Alabama Congressional District 5,371176,18454,5.0,13573,3.7,14345,3.9,49823,...,306571,2240,5790,3944,6521,9294,9285,11872,11610,4049

In [8]:
df_state.columns

Index(['fips', 'name', 'count_property', 'count_fema_sfha', 'pct_fema_sfha',
       'count_fs_risk_005_year00', 'pct_fs_risk_005_year00',
       'count_fs_risk_005_year30', 'pct_fs_risk_005_year30',
       'count_fs_risk_100_year00', 'pct_fs_risk_100_year00',
       'count_fs_risk_100_year30', 'pct_fs_risk_100_year30',
       'count_fs_risk_005_year00.1', 'pct_fs_risk_005_year00.1',
       'count_fs_risk_500_year30', 'pct_fs_risk_500_year30',
       'count_fs_fema_difference_year00', 'pct_fs_fema_difference_year00',
       'avg_risk_score_all', 'avg_risk_score_2_10', 'avg_risk_fsf_100_year00',
       'avg_risk_fsf_005_year0000', 'avg_risk_score_sfha',
       'avg_risk_score_no_sfha', 'count_floodfactor1', 'count_floodfactor2',
       'count_floodfactor3', 'count_floodfactor4', 'count_floodfactor5',
       'count_floodfactor6', 'count_floodfactor7', 'count_floodfactor8',
       'count_floodfactor9', 'count_floodfactor10'],
      dtype='object')

# Data Analysis

The data is provided from two different categories where one is FEMA and the other is First Street. The interactive dashboard is designed to display flood danger in the past, present, and future, paying close attention to current and anticipated environmental changes that could increase flood risk. Given that it is the first data of its sort to be made available for free across the country, the public's access to this information is advantageous to both property owners and the general public.

At a more detailed level, the findings highlight how unevenly different parts of the nation will be affected by shifting environmental circumstances. They also show that in order to adequately comprehend flood risk, additional localized data at the property level are required. The results of the Flood Factor at the property-level seem substantially different from how risk is viewed at the city, county, or state level. The Flood Factor, which ranges from 1 to 10, is a measure of a property's actual flood danger. Higher Flood Factors increase the likelihood that a property will flood, experience heavy floods, or both. The possible depth of a flood as well as the chance of flooding affect a property's Flood Factor.

The number of properties at any risk* flooding is determined using the First Street Foundation Flood Model. For instance, the research indicates that 439,300 properties in Alabama are at risk over the next 30 years when considering this higher degree of risk. 94,000 of these properties were classified as virtually certainly at risk, with a 99% likelihood that flooding will occur at least once over the following 30 years.
In the csv file attached to the zip are some of the columns which show the description

In [23]:
summary = pd.read_csv("s3://floodrisksummary/Dataset/Supporting_Documentation/FSF_AggregateDataCodebook_Flood_v2.0.csv")

summary

,Summary Column Header,Description
0,count_property,number of properties
1,count_fema_sfha,number of properties in FEMA SHFA
2,pct_fema_sfha,percent of properties in FEMA SFHA
3,count_fs_risk_005_year00,number of First Street properties with floodin...
4,pct_fs_risk_005_year00,percent of First Street properties with flood...
5,count_fs_risk_005_year30,number of First Street properties with floodin...
6,pct_fs_risk_005_year30,percent of First Street properties with floodi...
7,count_fs_risk_100_year00,number of First Street properties with floodin...
8,pct_fs_risk_100_year00,percent of First Street properties with floodi...
9,count_fs_risk_100_year30,number of First Street properties with floodin...
10,pct_fs_risk_100_year30,percent of First Street properties with floodi...
11,count_fs_risk_500_year00,number of First Street properties with floodin...
12,pct_fs_risk_500_year00,percent of First Street properties with floodi...
13,count_fs_risk_500_year30,number of First Street properties with floodin...
14,pct_fs_risk_500_year30,percent of First Street properties with floodi...
15,count_fs_fema_difference_year00,absolute difference in properties at risk betw...
16,pct_fs_fema_difference_year00,percent difference between number of First Str...
17,avg_risk_score_all,average risk score of all properties
18,avg_risk_score_2_10,"average risk scores from 2-10, excluding 1 (mi..."
19,avg_risk_fsf_100_year00,average risk score of properties with flooding...
20,avg_risk_fsf_500_year00,average risk score of properties with flooding...
21,avg_risk_score_sfha,average risk score of properties in a FEMA SFHA
22,avg_risk_score_no_sfha,average risk score of properties not in a FEMA...
23,count_floodfactor1,number of properties with a risk score = 1
24,count_floodfactor2,number of properties with a risk score = 2
25,count_floodfactor3,number of properties with a risk score = 3
26,count_floodfactor4,number of properties with a risk score = 4
27,count_floodfactor5,number of properties with a risk score = 5
28,count_floodfactor6,number of properties with a risk score = 6
29,count_floodfactor7,number of properties with a risk score = 7
30,count_floodfactor8,number of properties with a risk score = 8
31,count_floodfactor9,number of properties with a risk score = 9
32,count_floodfactor10,number of properties with a risk score = 10

# Data Visualization

The visualisation is accessible in the link below using an AWS EC2 Instance.

This is done using an Nginx redirect that has been configured in an Ubuntu instance. It is a t2.micro machine, runnning Ubuntu 18.04 with 12GB gp2 SSD storage.

http://54.85.139.41/dashboard